- README.md
- src/types.rs
- tests/test_types.rs
Closes #34 
I added a new `deserialize_with` function to the `serde` attributes of the different cutout fields in `types::Alert`. This new function, `deserialize_cutout_as_bytes`, extracts the image data from the inner cutout object and assigns it as the value of the deserialized field. No more inner type with a filename field.
I've also made some updates to the `README.md` file to clarify a couple points.
> 34 ignore filenames

- Cargo.lock
- Cargo.toml
- src/alert.rs
- src/alert_worker.rs
- src/bin/alert_worker.rs
- src/conf.rs
- src/fake_ml_worker.rs
- src/filter_worker.rs
- src/lib.rs
- src/scheduling.rs
- src/testing_util.rs
- src/types.rs
- tests/test_types.rs
Closes #67
Normally I don't commit changes like I did here ("pile o changes"), I try to make the commit history a little more semantic for easier review. But in the interest of time, I'll try to summarize what was done here.
The main change was adding new `AlertError` and `AlertWorkerError` types. Errors encountered in both `alert_worker` and `process_alert` are converted into one of the variants of these types, either automatically via the `From` impl provided by `thiserror` or explicitly via `map_err`, and then we propagate the error back to the caller using the `?` syntax. This is all done instead of calling `unwrap`, which would cause the program to panic if there's an error.
There's some stuff I did in the scheduler, including taking out the mutex on the receiver which we didn't …
> Add error types to the alert worker system

- src/alert_worker.rs
- src/db.rs
@Theodlz let me know whether this is helpful.
It looks like `db::create_index` might be a general-purpose thing, so this is the kind of function where it's good to wrap the 3rd party error (`mongodb::error::Error`) in our own type, so I made a simple tuple struct named `CreateIndexError`. In `alert_worker`, there are five different places where `create_index` is called, so I _could_ have added five new variants to the `AlertWorkerError` enum corresponding to those failure cases. However, I'm not sure we really care whether it's one index vs another that failed to be created, so I'm simply wrapping the `db::CreateIndexError` in `AlertWorkerError::CreateIndexError`. We can always change this in the future if we need more granularity.
You'll notice I got rid of the call to `error!` in …
> handle index creation errors

- src/alert.rs
- src/alert_worker.rs
- src/db.rs
- src/lib.rs
This PR adds:
- a `coordinates.radec_geojson` field on the alert_aux entries to allow direct object-level queries. One issue we noticed in Kowalski is that folks might want to simply query for objects (often even just their names) without having to query for alerts (where you have multiple entries for the same object). This will also speed up the survey <-> survey cone searches we'll have to do for ZTF + Rubin operations, so we can query a table of N objects rather than a table of N * M alerts.
- We take advantage of this PR to properly add code to create the 2dsphere indexes we need to query the tables with cone searches, which was missing so far. For that we add a new `db.rs` file with a method to create indexes given a collection, and an index details' as a bson document
TODO: think …
> GeoJSON index on aux table + db utils

- Cargo.lock
- Cargo.toml
- src/fake_ml_worker.rs
- src/fits.rs
- src/lib.rs
This PR adds the code we need to:
- read the image data from the gzipped cutouts we get in the alert packets
- normalize the image data using the [Frobenius norm](https://www.wikiwand.com/en/articles/Matrix_norm#Frobenius_norm)
- a method that takes an alert bson document and returns the image data for all 3 cutouts as a triplet of images
- calls said method in the ML worker.
TODOs:
Future PRs will keep improving the ML worker until we can do actual ML with it, calling models. We'll start with BTSbot, which is the model we already make the most use of in production w/ Kowalski and a great way to show BOOM's capabilities.
*PS: here we take a lot of shortcuts when reading the FITS data. Instead of having a generic fits file handling, since we know what the actual data looks like ahead of …
> FITS utils - read img data from Alerts

- src/alert/base.rs
- src/alert/lsst.rs
- src/alert/ztf.rs
- tests/test_lsst.rs
Here we:
- add the magnitude data for the aperture photometry
- convert all MJD fields from LSST to JD
- remove the provided SNR, replace it with the one we calculate from the reported flux and fluxerr (psf)
- remove some bad pixel flags that are redundant
- remove the "snaps" based photometry (whatever it might be lol)
- add the "3 closest objects" data to the `DiaObject` (will use it in the future).
- convert the ZTF `fid` (filter/band id) field to `band` as a string, similar to LSST
- ZTF's `ssnamenr`, avoid values such as "null" (as a str), making sure it is None/null when it should be.
- removed a number of ZTF alert fields (magdiff, classtar, magfromlim, aimagerat, bimagerat, sumrat, magapbig, sigmagapbig, jdendhist, tooflag, objectidps1, objectidps2, objectidps3, nmtchps, rfid, …
> Additional conversions (magap, jd, ...) to LSST schema

- src/bin/scheduler.rs
- src/lib.rs
- src/scheduler/base.rs
- src/scheduler/mod.rs
At the moment some methods to spawn a scheduler are found directly in the `bin/scheduler.rs`, and most of the scheduling code is located in `utils/scheduling.rs`. Also, we have a number of unwraps in there which isn't ideal.
In this PR we create a dedicated `scheduler` module, move all functions but main found in the binary to this new module, add better error handling and a dedicated scheduler error type.
PS: Will point to main once other PRs that this one depends on have been reviewed, right now I'm forced to point to another branch to not show changes that are irrelevant to this PR
> Scheduler Error Handling + dedicated module

- .gitignore
- Cargo.lock
- Cargo.toml
- src/alert/base.rs
- src/alert/lsst.rs
- src/alert/mod.rs
- src/alert/ztf.rs
- src/utils/testing.rs
- tests/test_lsst.rs
- tests/test_ztf.rs
This PR is a quick attempt at addressing #102. Here are some notes;
- avro uses variable length + zigzag encoding for its long data type (equivalent of i64 in rust). So unlike String values we can't just convert to bytes and look for those in the bytes of an avro file, we need to encode it first.
- for the same reason, when randomizing new candid values (and object id for lsst) the new values need to be in a similar range as the original values, as they would otherwise result in a different number of bytes and that creates an error when we try to replace existing bytes with the new ones.
- this could easily be solved by changing how we replace the existing bytes. Instead of just replacing them we could split the bytes input in 2 around the existing value, and append/prepend around the new …
> Testing utils - Alert Randomizer

- src/kafka/ztf.rs
In this PR, we tweak some of the parameters of the `librdkafka` producer to improve the performance when pushing messages to a topic. Before these changes producing speeds would be ~around 5.5s for 1000 messages, now we're around ~250ms for the same volume, which is ~20x faster. In another PR we should consider making similar config changes to the producer used to push alerts that pass filters to kafka (introduces in PR #97), but due to message size and volume it is only critical for the `produce_from_archive` method at the moment.
Solves part of issue #101 (persistence is missing still, should be added in another PR).
BTW kafka optimizing isn't an exact science, it requires one to do a number of trials to finetune numbers. I am sure that speed could be even better, but this is already so …
> Kafka "produce_from_archive": performance improvements

- src/kafka/ztf.rs
I noticed that if I had a non-avro file in the same dir as the alerts (say the original .tar.gz file from the ZTF archive), the producer tried to load it in memory which creates massive memory issues.
This PR simply makes sure that we skip non `.avro` files
> Kafka producer bugfix: avro files only

- src/alert/base.rs
- src/alert/lsst.rs
- src/alert/ztf.rs
This PR addresses issues #112  and #114.
For #112, the solution was that while some old avro spec stack overflow I read claimed that the block size detail was contained in a fixed 4 bytes, it was actually made of 2 variable length zigzag encoded long values (so avro's way of storing a simple i64 value, where it only uses the number of bytes required to encode the value => small value = less bytes):
- the first tells us how many records are in the next data block, which we can also double check is equal to 1 for our purpose.
- the second tells us the total length in bytes of the records in that block, useless for us.
So to fix that issue we replace the 4 bytes read by a proper decoding of these variable length values. We could quite frankly just read the 1 byte for the number of records …
> ZTF processing: various bugfixes.

- src/alert/base.rs
- src/alert/lsst.rs
- src/alert/mod.rs
- src/alert/ztf.rs
- src/utils/testing.rs
- tests/test_ztf.rs
@jesaerys please take a look, in this PR I:
- moved the lsst crossmatching code to its own function
- added a const for the radius, right now it looked like you were grabbing a somewhat random number from the crossmatch config that could have been anything and likely unrelated to LSST
- changed the alert randomizers to randomize the ra/dec by default otherwise tests generate stuff at the same positions so that messes things up. Here I randomize everything and then set the dec to a fixed value because otherwise it could be randomized above 33.5 dec while would always result in no matches. A unit test for the > dec case would be a nice addition actually
- fixed the index that was set to unique which is not necessary and actually incorrect (seems due to astrometry, pipelines and such you …
> Alert stream crossmatching: bugfixes, cleanup, and unit test improvement

- config.default.yaml
- src/alert/base.rs
- src/bin/kafka_consumer.rs
- src/conf.rs
- src/filter/base.rs
- src/kafka/base.rs
- src/kafka/lsst.rs
- src/kafka/ztf.rs
- src/ml/base.rs
- src/utils/testing.rs
In this PR, we make the redis connection configurable from the config file (defaulting to the usual localhost) just like the MongoDB connection already was, and replace all occurences of a hardcoded connection to redis with a call to that new function.
Addresses issue: https://github.com/boom-astro/boom/issues/121
> Redis connection: configurable

- README.md
This PR removes the outdated Python virtual environment setup instructions from the README, following recent changes and discussion in PR #128 and #133.
> Clean up outdated Python setup and clarify Kafka usage in README

- Cargo.lock
- api/Cargo.toml
- api/src/api/alerts.rs
- api/src/api/filters.rs
- api/src/api/query.rs
- api/src/conf.rs
- api/src/lib.rs
- api/src/main.rs
- api/tests/test_query.rs
Resolves https://github.com/boom-astro/boom-api/issues/7
I also refactored to pass around a `Database` object instead of a `Client` object, since there were many instances where the client was used to create a database from `DB_NAME`.
> Read database parameters from config file

- Cargo.lock
- api/Cargo.toml
- api/src/main.rs
While reviewing #141, I found it very useful to see logs of what I was trying through an API client. This PR adds some basic logging based on the official actix web example: https://actix.rs/docs/middleware/#logging
The formatting is simple but effective (ala nginx), as it records the endpoints being hit, the IP it came from, the time it took to respond, the response status, ...
PS: We might want to NOT use env_logger and somehow use tracing to make it look like the logging system of the rest of boom.
> API: Basic logging

- CONTRIBUTING.md
- Cargo.lock
- Cargo.toml
- README.md
- src/alert/base.rs
- src/alert/lsst.rs
- src/alert/mod.rs
- src/alert/ztf.rs
- src/bin/scheduler.rs
- src/conf.rs
- src/filter/base.rs
- src/ml/base.rs
- src/scheduler/base.rs
- src/utils/db.rs
- src/utils/mod.rs
- src/utils/o11y.rs
- src/utils/spatial.rs
- src/utils/worker.rs
- tests/test_lsst.rs
- tests/test_ztf.rs
Closes #105.
There's a lot going on in this PR. Highlights:
* The tracing subscriber has been configured so that each log line includes the thread name, the module name/file name/line number where the event was emitted, and span details (which spans were in scope and any context/fields associated with them). Examples are shown (way, way) below.
* Many of our functions and methods now have the `tracing::instrument` attribute, which automatically creates a span for whatever it's attached to. Spans are nice because they collect values stored in fields (e.g., function arguments), which help provide context for events. They're also nice because we can configure the subscriber to show events when spans open/enter and close/exit, helping us understand where in the flow of our program various …
> Instrumentation and logging

- Dockerfile
- docker-compose.default.yaml
This is set up to be able to build a different image for each executable, e.g., with `docker build --target api -t boom-api .`. I've never done this before, but it looks pretty convenient since Docker Compose can set the `target` as a build arg:
```yaml
services:
api:
build:
context: .
dockerfile: Dockerfile
target: api
image: boom/boom-api:latest
ports:
- "4000:4000"
scheduler:
build:
context: .
dockerfile: Dockerfile
target: scheduler
image: boom/boom-scheduler:latest
```
The ultimate goal is to be able to run the entire app (all services) with `docker compose up`, merging in a separate dev Docker Compose config for local development, which would ideally use `cargo-watch` and mount the local working directory.
> Add Dockerfile

- Cargo.lock
- Cargo.toml
Closes #169
I don't really understand why, but doing a `cargo update` fixed the issue I was seeing in #169. I didn't touch any libs on my system and I didn't alter our `Cargo.toml` (except for `ort`/`ort-sys`; see below), so the only thing that changed was a bunch of little version bumps across many transitive dependencies. Clearly this had some kind of effect on `reqwest`/`hyper` way deep down inside.
One package that got bumped was `ort-sys` (a dependency of `ort`) from 2.0.0-rc.9 to 2.0.0-rc.10. It turns out that this version causes `cargo build` to fail, either because there's an issue with `ort-sys` 2.0.0-rc.10 or because `ort` 2.0.0-rc.9 is incompatible with it. The bump happened because `ort`'s `Cargo.toml` lists `ort-sys = "2.0.0-rc.9"`, i.e., a "caret requirement" allowing any …
> Pin ort-sys and cargo update

- src/bin/kafka_consumer.rs
- src/kafka/lsst.rs
- src/kafka/ztf.rs
There is some confusion in the kafka consumer structs and associated binary, as we used to be able to pass custom topics to read from (useful before we were able to automagically infer the topic name from a date) but for ZTF the parameter still existed but was ignored, and for LSST it still existed when we always want to read from the same one topic which holds the simulated data from Rubin.
This in this PR:
- remove the unused topic parameter from the `new` function to instantiate the `ZtfAlertConsumer`
- replace the `topic` parameter by a safer and more explicit `simulated` (bool) parameter which for now we forced to true, and will change to a clap parameter once we have real LSST data and an associated topic to read from.
> Kafka Consumer: custom vs hardcoded topic bugfix

- Cargo.lock
- Cargo.toml
- src/alert/base.rs
- src/alert/mod.rs
- src/bin/scheduler.rs
- src/ml/base.rs
- src/ml/models/acai.rs
- src/ml/models/base.rs
- src/ml/models/btsbot.rs
- src/ml/ztf.rs
- src/utils/spatial.rs
- tests/test_ztf.rs
In this PR we:
- update to ort version rc10 + fix some breaking changes
- conditional dependencies declaration for the execution provider features of ort, to add the coreml feature on macos and cuda on linux. Previously we could not take advantage of the coreml API on mac as adding it as a feature to Cargo.toml caused the build to fail on non-mac systems
- conditionally register the execution provider based on the target os (same logic as for the dependency)
- added instrumentation to all ML worker methods for which monitoring performance at our stage of the development can prove useful (which for now, is most!).
Also (and somewhat unrelated to this one):
- we wrap some of the code in the  main loop of the `run_alert_worker` function, so we can have a slightly better coverage of the …
> ML dependency update + coreml support

- src/ml/base.rs
Closes #182 
The main fix is in the first commit, 09cee74. We now use `saturating_sub` so that decrementing the counter evaluates to zero instead of panicking when the number of candids processed is greater than the counter's value.
The next commit, 3339df3, simplifies the manipulation of the counter. Looking at the code, I realized we didn't need to have little +1/-1 offsets. Hopefully this clarifies the logic a little.
Finally, commit b48f2ce simplifies things a little more by removing what appears to be a redundant check of whether there are any candids to process. In the original code, we first checked the length of the queue, handled the empty-queue case, then later popped from the queue and did another check to handle the empty-vector case. Both checks amount to the same thing, so …
> Fix subtraction overflow in ml worker

- Cargo.lock
- Cargo.toml
- docker-compose.default.yaml
- src/bin/kafka_consumer.rs
- src/bin/kafka_producer.rs
- src/kafka/base.rs
- src/kafka/lsst.rs
- src/kafka/ztf.rs
Closes #170.
The call to `consumer.subscribe` is removed so that `consumer.assign` can work properly. tl;dr `subscribe` and `assign` are incompatible APIs, and calling `subscribe` was preventing the subscriber from using the timestamp-based offsets we assign to it. See https://github.com/boom-astro/boom/issues/170#issuecomment-3034302595 for a more detailed explanation.
I've run this a number of times on the same topic (only running the producer once, not touching the topic after that), and it has worked every time. *If* there is still an issue with the consumer, I'm confident that it's going to be pretty rare.
Other changes in this PR:
* I Added some tracing stuff for rdkafka/librdkafka so we can now optionally log their events. For instance, by setting …
> make consumer able to use given offsets

- src/alert/decam.rs
- src/alert/lsst.rs
- src/alert/ztf.rs
- src/ml/ztf.rs
- src/utils/db.rs
In this PR:
- we fix the update_timeseries_op() function, where a missing `$` in front the name of the array field to update broke that function
- the $sortArray operator used by update_timeseries_op() is only supported in aggregation pipelines, so we turn the update document passed to the `update_one()` method into a vec of doc, i.e. an aggregation pipeline used for update. *Note: the performance impact of that change is unknown and will be assessed using Pete's benchmarking suite in `boom-astro/boom-paper`*.
- we handle a potential edge-case where we try to update an array with new entries, but that array does not exist yet (in which case we want to avoid an error and proceed as usual). *Note: The logic there could be improved to use a simple insert of the new values when the field is …
> Timeseries update: fix + improvements

- .github/workflows/test-throughput.yaml
- tests/throughput/compose.yaml
Looks like we weren't able to read the baseline wall time number from main, this PR fixes this.
Also, we make the CI fail if the time we take with the PRs code is more than `TOLERANCE_PERCENTAGE` % slower, where for now `TOLERANCE_PERCENTAGE=5.0%` (should be tuned based on the standard deviation we observe in the next few PRs).
Last but not least, we stop mapping container ports to the host. It's useless, and can create conflicts if you have other services running on the same machine.
> Throughput reports bugfix

- src/alert/lsst.rs
- src/alert/ztf.rs
This PR adds the `classtar` field back to the ZTF candidate schema, also adds a missing `serde rename` macro on the `is_dipole` field (which is named `isDipole` in the schema).
> Add back `classtar` to the ZTF candidate schema
